### PR TITLE
(208) fix typogarphical nits

### PR DESCRIPTION
**Pull request by bobsut**
apostrophectomy
consistentize whitespace
addresses https://github.com/krlawrence/graph/issues/208

### CODE REVIEW

**Comment by krlawrence** [comment]
Thanks for submitting these. Will merge in.

**Comment by krlawrence** [comment]
The two spaces at the end of the line for markdown files is intentional to force a newline

**Comment by bobsut** [comment]
Do you want me to restore the line-terminating double spaces where needed, and push a new commit to this branch?

**Comment by krlawrence** [comment]
Yes please as I cannot merge this as it stands as it will break all the markdown files.

**Pull request merged**
